insert into message(id, header, body) values (0, 'Header1', 'Hello!');
insert into message(id, header, body) values (1, 'Header2', 'Good bye!');
insert into message(id, header, body) values (2, 'Header3', 'This is test');
insert into message(id, header, body) values (3, 'Header4', 'Hmm?');
insert into message(id, header, body) values (4, 'Header5', 'Trolololo.');
insert into message(id, header, body) values (5, 'Header6', 'Witam.');
insert into message(id, header, body) values (6, 'Header7', 'Czy nosorożce mają uczucia?');
insert into message(id, header, body) values (7, 'Header8', 'doh.');
insert into message(id, header, body) values (8, 'Header9', 'blah blah.');
insert into message(id, header, body) values (9, 'Header10', 'Some message blah blah blah again.');
insert into message(id, header, body) values (10, 'Header11', 'Hello hello hello hello!');
insert into message(id, header, body) values (11, 'Header12', 'Czy to ma sens co robimy?');
insert into message(id, header, body) values (12, 'Header13', 'This is test (again).');
insert into message(id, header, body) values (13, 'Header14', 'Hmm?');
insert into message(id, header, body) values (14, 'Header15', 'Być albo nie być..');
insert into message(id, header, body) values (15, 'Header16', 'I like coding.');
insert into message(id, header, body) values (16, 'Header17', 'Z tymi nosorożcami dalej nie wiem.');
insert into message(id, header, body) values (17, 'Header18', 'XXX.');
insert into message(id, header, body) values (18, 'Header19', 'No more ideas for messages.');
insert into message(id, header, body) values (19, 'Header20', 'The end.');